# Generated by Django 6.0.7 on 2026-08-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_expense_sponsorshiprevenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, help_text='Registrations close after this date/time. Leave blank for no deadline.', null=True),
        ),
    ]
