# Generated by Django 6.0.7 on 2026-08-12 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_eventmember_academic_year_eventmember_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('av_equipment', 'AV Equipment'), ('furniture', 'Furniture'), ('signage', 'Signage & Banners'), ('catering_supplies', 'Catering Supplies'), ('safety', 'Safety Equipment'), ('other', 'Other')], default='other', max_length=30)),
                ('total_quantity', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('capacity', models.IntegerField(default=0)),
                ('amenities', models.TextField(blank=True, help_text='Comma-separated, e.g. Projector, AC, Sound System')),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('maintenance', 'Under Maintenance')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_allocations', to='event.event')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='event.resource')),
            ],
            options={
                'ordering': ['-allocated_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='venue_ref',
            field=models.ForeignKey(blank=True, help_text='Optional: link to a registered Venue for capacity/availability tracking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_booked', to='event.venue'),
        ),
    ]
