# Generated by Django 6.0.7 on 2026-08-12 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_resource_venue_resourceallocation_event_venue_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sponsor_logos/')),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='sponsorshiprevenue',
            name='sponsor_ref',
            field=models.ForeignKey(blank=True, help_text='Optional: link to a registered Sponsor for reusable profile/logo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsorships', to='event.sponsor'),
        ),
    ]
