# Generated by Django 6.0.7 on 2026-08-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_sponsor_sponsorshiprevenue_sponsor_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='contract_document',
            field=models.FileField(blank=True, help_text='Upload signed contract/agreement (PDF, DOC, etc.)', null=True, upload_to='vendor_contracts/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
