# Generated by Django 6.0.7 on 2026-08-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_vendor_contract_document_vendor_contract_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='invoice',
            field=models.FileField(blank=True, help_text='Upload invoice/receipt (PDF, image, etc.)', null=True, upload_to='expense_invoices/'),
        ),
    ]
