# Generated by Django 6.0.7 on 2026-08-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_expense_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='amenities',
        ),
        migrations.AddField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='has_ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='has_projector',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='has_sound_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='has_stage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_type',
            field=models.CharField(choices=[('auditorium', 'Auditorium'), ('classroom', 'Classroom'), ('lab', 'Lab'), ('ground', 'Ground/Field'), ('hall', 'Seminar Hall'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
