# Generated by Django 6.0.7 on 2026-08-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_remove_venue_amenities_venue_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermark',
            name='checked_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
