# Generated by Django 6.0.7 on 2026-08-29 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_remove_contactmessage_is_reviewed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('event_rules', 'Event Rules'), ('registration', 'Registration'), ('cancellation', 'Cancellation'), ('refund', 'Refund'), ('qr_checkin', 'QR Check-in'), ('code_of_conduct', 'Code of Conduct'), ('privacy', 'Privacy'), ('terms', 'Terms & Conditions'), ('other', 'Other')], default='other', max_length=30)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Policies',
                'ordering': ['category', 'title'],
            },
        ),
    ]
