# Generated by Django 6.0.7 on 2026-08-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='ticket_code',
            field=models.CharField(blank=True, help_text='Unique auto-generated ticket code, e.g. M-7X92K4', max_length=20, null=True, unique=True),
        ),
    ]
