# Generated by Django 6.0.7 on 2026-09-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_eventmember_ticket_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='points_awarded',
            field=models.BooleanField(default=False, help_text='True once event points have been credited for a Present mark — prevents duplicate awarding.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_points',
            field=models.IntegerField(default=0, help_text='Cumulative points awarded from event attendance.'),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='ticket_code',
            field=models.CharField(blank=True, help_text='Unique auto-generated ticket code, e.g. MEMBER-7X92K4', max_length=20, null=True, unique=True),
        ),
    ]
